aconv-chans: 10
aconv-filts: 100
adim: 1024
atype: location
batch-size: 16
dlayers: 2
dropout-rate: 0.2
dunits: 1024
elayers: 5
epochs: 10
eprojs: 1024
etype: vggblstm
eunits: 1024
maxlen-in: 800
maxlen-out: 150
mtlalpha: 0.5
opt: adadelta
patience: 3
sampling-probability: 0.0
sortagrad: 0
subsample: '1_2_2_1_1'
